<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>box_otp4</name>
   <tag></tag>
   <elementGuidId>d1a39e00-8880-4c95-8ad2-f2f066069ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06ea824c-38f2-433c-837a-e2e2dc0f5070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp4</value>
      <webElementGuid>499af7cd-e354-4c99-9f81-5d110720bf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5d1de3b2-89c5-4713-abdb-390fd5544efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>071a6745-40bb-410b-88a3-dee986437770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6edafc24-3de4-4143-8f4e-692f65b1b83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dcf26bcd-6451-4539-9c1a-d3e5e0101877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>4a7979f1-8d5d-43fc-abea-788461167add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 bg-transparent w-14 h-14 text-sm tracking-widest font-bold text-center focus:outline-none border border-opacity-50 rounded-xl p-0 mb-2 text-white border-gray-400 border-opacity-20</value>
      <webElementGuid>c6be6101-0ddb-4372-a530-676059b9b5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp4&quot;)</value>
      <webElementGuid>25af5239-1a9c-4de6-a190-515022f34eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp4']</value>
      <webElementGuid>11fce432-5c6f-492d-87cb-424d00ed4050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div[2]/div/div[2]/form/div/input[4]</value>
      <webElementGuid>001141bd-abfb-4fd2-9ecc-c31d33a8f217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>dccc26ce-0103-4b68-9fc2-b9b2e1f74f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp4' and @type = 'text' and @placeholder = '-']</value>
      <webElementGuid>17bb3fd7-7a63-470b-b5bb-7518466bc480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
