<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>box_otp2</name>
   <tag></tag>
   <elementGuidId>0113de83-6cea-4397-8b34-b0a52e1c8161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f686d42b-e42c-4fec-996d-088fa3631a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp2</value>
      <webElementGuid>51bddbf8-c307-47b1-94b1-0b40b8a42cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e8985ed1-99e0-4ea3-95cb-4343ac6a16c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d65169f-0f15-4b3e-8946-dc15d4967f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5433fb74-2035-4df4-8c64-37cf4efd46ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87ecfc91-7eba-4494-9f7d-5ebccf1eb9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>c93ee92b-4c00-4d87-8ef8-b6fdcf0e89fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 bg-transparent w-14 h-14 text-sm tracking-widest font-bold text-center focus:outline-none border border-opacity-50 rounded-xl p-0 mb-2 text-white border-gray-400 border-opacity-20</value>
      <webElementGuid>7ae2a6d1-7a51-4442-9925-dda7aa088660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp2&quot;)</value>
      <webElementGuid>a5f40dd4-03be-49b3-8044-235d396873cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp2']</value>
      <webElementGuid>fd23b2de-c554-44b2-9e8e-5c21726b9ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div[2]/div/div[2]/form/div/input[2]</value>
      <webElementGuid>d770b93f-f3b0-4227-a4d5-8eff27fb46c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>5d56d68b-c09a-4955-ae27-41260c6c8795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp2' and @type = 'text' and @placeholder = '-']</value>
      <webElementGuid>b210381c-1c87-4704-9ed8-39bab795f17c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
