<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>box_otp1</name>
   <tag></tag>
   <elementGuidId>278059a0-53fb-434e-b63f-c9208ba70272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53e8450c-8811-46df-93cc-89efa0eeb6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp1</value>
      <webElementGuid>67aeaa04-a1d0-43ae-b08c-3b0826d9eb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>601f04a9-3257-4119-873c-3555942fa99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4eea215b-ed62-4601-9507-9b3925618f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdd2de92-a739-473c-bcbe-1cfc5d4fa101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6ab9b14c-0170-4939-af0c-529c2aae20ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>67c6bec3-c289-4f8b-a142-f82fb0d87a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 bg-transparent w-14 h-14 text-sm tracking-widest font-bold text-center focus:outline-none border border-opacity-50 rounded-xl p-0 mb-2 text-white border-gray-400 border-opacity-20</value>
      <webElementGuid>1e82b405-84c9-451e-826e-5f20aadc2d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp1&quot;)</value>
      <webElementGuid>998e473f-3d7e-4083-84d8-8a91f708c28a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp1']</value>
      <webElementGuid>b065de73-606c-4545-83be-029e1c7f7728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div[2]/div/div[2]/form/div/input</value>
      <webElementGuid>4b1babcf-2cca-429e-a8ae-a8092ee63d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dd23ccb4-7071-4032-8536-0e4e14ca0f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp1' and @type = 'text' and @placeholder = '-']</value>
      <webElementGuid>2e85c836-e113-45b9-bab9-74520f7d209a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
