<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_checkDaftar berhasil</name>
   <tag></tag>
   <elementGuidId>bd5b9c81-db4f-42de-ae69-2940c948ad76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.toasted.custom-toast.toasted-primary.default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kjqnMsVv4']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a390be25-96cc-4324-9e8e-0d3fa5288144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toasted custom-toast toasted-primary default</value>
      <webElementGuid>de878bb4-3f02-45e3-abdd-9c5ef5269fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>checkDaftar berhasil</value>
      <webElementGuid>07a2bb51-d6a9-4fda-a429-b3ce4fc7924f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kjqnMsVv4&quot;)/div[@class=&quot;toasted custom-toast toasted-primary default&quot;]</value>
      <webElementGuid>5eb1f094-60e2-4180-8320-6e8fc31c29cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kjqnMsVv4']/div</value>
      <webElementGuid>b32ca76f-c0be-4f60-9fb0-8bc44670acbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[1]/following::div[2]</value>
      <webElementGuid>6989e140-3f72-4379-980e-7372b69dca78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Film Saya'])[2]/following::div[2]</value>
      <webElementGuid>0659a22d-da02-48ff-bbaa-4e9bc2b40e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar berhasil']/parent::*</value>
      <webElementGuid>5fb0331f-5b0f-40e9-ad1a-d3db320c1024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>9c22d254-631d-47fc-b01c-a1d707f2d80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'checkDaftar berhasil' or . = 'checkDaftar berhasil')]</value>
      <webElementGuid>63b38267-c492-4b5c-b1ce-d4dfd5e11608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
