<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_2431</name>
   <tag></tag>
   <elementGuidId>8e6a55b9-4e7b-4d00-a486-ab2a91420fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td/div[2]/div[2]/div/div[3]/div[1]/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[1]/div[1]/div[1]/table[2]/tbody/tr[3]/td/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c818f6a0-e8f2-4be4-9679-312c8c20f000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        2431
                    </value>
      <webElementGuid>6e2c3931-5635-41c1-856f-e43c566ccc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:6o&quot;)/div[1]/div[1]/div[1]/table[2]/tbody[1]/tr[3]/td[1]/p[1]</value>
      <webElementGuid>3acdbbd9-7b83-4267-abe0-c975fe33ee7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':6o']/div/div/div/table[2]/tbody/tr[3]/td/p</value>
      <webElementGuid>ab69f11f-472e-4987-9e37-5a410bea8820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halo tes akun,'])[1]/following::p[2]</value>
      <webElementGuid>9e9aaed9-f37e-4cd5-a740-d3efbb5b6b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[4]/following::p[2]</value>
      <webElementGuid>b3c966f4-83e9-43cc-a58b-36ee0cdde7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bioskop'])[5]/preceding::p[2]</value>
      <webElementGuid>62d8183d-ac76-4e5f-b2a5-424a9978df97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2431']/parent::*</value>
      <webElementGuid>3b6cb083-7789-4e78-91b7-92f55b1f937d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/p</value>
      <webElementGuid>1390d6a5-f0c2-4f73-8fb2-7de8224fe179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                        2431
                    ' or . = '
                        2431
                    ')]</value>
      <webElementGuid>3462976b-a728-4717-955b-7e0596fa60ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
