<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aktivasi Akun Bioskop Online</name>
   <tag></tag>
   <elementGuidId>9ff2602b-6330-4fdb-8b02-aa735860af96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[2]/div[5]/div[1]/div/table/tbody/tr/td[5]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb88aaa9-5258-4364-a4d0-497c0f5e77c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bqe</value>
      <webElementGuid>f9c52cfb-b438-4225-814c-e200f9d8162f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thread-id</name>
      <type>Main</type>
      <value>#thread-f:1755317392702092359</value>
      <webElementGuid>a553c3b9-6142-43c2-b5bb-ba9ed8adf3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-thread-id</name>
      <type>Main</type>
      <value>185c23de5c12b447</value>
      <webElementGuid>67bcd187-6a68-48cb-9384-fc79ae2a9354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-message-id</name>
      <type>Main</type>
      <value>185c23de5c12b447</value>
      <webElementGuid>b1150009-9d24-4f85-94d6-0bf25a826dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-non-draft-message-id</name>
      <type>Main</type>
      <value>185c23de5c12b447</value>
      <webElementGuid>931d50dc-acfe-4ac0-b6f6-e614cd9f2ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktivasi Akun Bioskop Online</value>
      <webElementGuid>c5f605b3-e7e0-42fa-8a3c-dd0da23f81fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:5m&quot;)/span[@class=&quot;bqe&quot;]</value>
      <webElementGuid>7b9aa87b-6d24-4c28-baef-061743d99340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id=':5m']/span</value>
      <webElementGuid>41045c68-2da7-4ed7-87ea-9dfc665d94fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[2]/following::span[2]</value>
      <webElementGuid>af45ecdc-dfef-42fe-a936-d90ad2f839cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BioskopOnline'])[4]/following::span[2]</value>
      <webElementGuid>f35cf02c-dfdd-451c-924f-54a937d0874b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktivasi Akun']/parent::*</value>
      <webElementGuid>a35c8347-daf1-4eed-91bb-ce69e2ac4950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div[2]/span/span</value>
      <webElementGuid>c2841b0a-5cd9-4563-8488-ecbf515a9a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Aktivasi Akun Bioskop Online' or . = 'Aktivasi Akun Bioskop Online')]</value>
      <webElementGuid>89950aa0-ba68-46d5-a5fe-adaef757b05f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
